### ISSUE TITLE
Couldn`t delete span

### ISSUE THREAD

**Issue by nAkhmedov** [splitwise/TokenAutoComplete#150] opened 2015-07-20 09:15 UTC
I have a more than 1 spans and i moved focus to next view. In a result TokenCompleteTextView displays like that contect +2, and go back to first editText, try to delete expandable spans. It deletes one by one words not span itself. In this situation only first spans deleted itself.

**Comment by mgod** [comment] 2015-07-22 14:12
I'm not sure what you mean by "deletes one by one words" – can you give me steps to see the error using the example project?

**Comment by nAkhmedov** [comment] 2015-07-23 07:30
When you go back spans editText(test@example.com +3) after moving focus, try to delete spans. I couldn`t delete spans, it deletes by words only

**Comment by mgod** [comment] 2015-08-20 16:03
Sorry for the slow follow-up. I'm still not able to reproduce this. It's possible it's device or simulator specific? When I go to the simulator, add a few spans, then lose focus, I'm able to delete the spans when I go back to the field.

**Comment by jakubbroz** [comment] 2015-09-21 14:41
https://youtu.be/EcaD7EYy1BY

**Comment by nAkhmedov** [comment] 2015-09-25 08:36
https://www.youtube.com/watch?v=69vKJ3phoR4&feature=youtu.be

**Comment by mgod** [comment] 2015-09-28 20:05
I'm still not able to reproduce the issue where nothing would get deleted (though I did just fix some editing issues, so you might find the current master/HEAD version fixed this). For the delete-by-words issue, it looks like you have the ```TokenDeleteStyle``` set to ```ToString```. Can you set it to ```Clear``` and see if this resolves the issue?

**Comment by nAkhmedov** [comment] 2015-09-29 04:42
I am using

**Comment by mgod** [comment] 2015-09-29 15:09
It's the TokenDeleteStyle that matters for this.

**Comment by nAkhmedov** [comment] 2015-10-12 10:35
I have set ```view.setDeletionStyle(TokenCompleteTextView.TokenDeleteStyle.
Clear);``` but it couldn't help me :(

2015-09-29 20:09 GMT+05:00 Marshall Weir <notifications@github.com>:

**Comment by mgod** [comment] 2019-03-09 16:21
I think this has been fixed in version `3.0.0`, but I'm still not able to reproduce the issue. Please let me know if you're still seeing this problem.

**Closed by mgod** 2019-03-09 16:21 UTC
Labels: bug, need feedback
