### ISSUE TITLE
when i am clicking outside of selected token in Edittext, my selected token deleted

### ISSUE THREAD

**Issue by Danish1111** [splitwise/TokenAutoComplete#342] opened 2018-03-09 09:32 UTC
anyone know how to fix it. i mean i want to delete token when user actually click on token . not outside token.

**Comment by mgod** [comment] 2019-03-09 15:58
Duplicate of #99.

**Closed by mgod** 2019-03-09 15:58 UTC

**Comment by AdilSaiyad** [comment] 2019-08-30 08:01
I am facing the same issue on this, Did it solved?
