### ISSUE TITLE
ANR  when Collapse

### ISSUE THREAD

**Issue by lpflpy** [splitwise/TokenAutoComplete#290] opened 2017-02-22 07:03 UTC
Exception: application is no response, the stacktrace like this: 

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.386  android.graphics.Paint.getFontMetricsInt(Native Method)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.386  android.text.MeasuredText.addStyleRun(MeasuredText.java:191)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.387  android.text.MeasuredText.addStyleRun(MeasuredText.java:281)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.387  android.text.StaticLayout.generate(StaticLayout.java:745)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.387  android.text.DynamicLayout.reflow(DynamicLayout.java:300)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.387  android.text.DynamicLayout.access$000(DynamicLayout.java:36)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.388  android.text.DynamicLayout$ChangeWatcher.reflow(DynamicLayout.java:662)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.388  android.text.DynamicLayout$ChangeWatcher.onSpanChanged(DynamicLayout.java:691)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.388  android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1077)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.388  android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:637)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.389  android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:567)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.389  android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:225)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.389  android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:34)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.389  com.tokenautocomplete.TokenCompleteTextView.removeSpan(TokenCompleteTextView.java:1020)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.390  com.tokenautocomplete.TokenCompleteTextView.performCollapse(TokenCompleteTextView.java:776)

02-22 15:00:26.397 27569 27705 I AnrError: 02-22 15:00:26.390  com.tokenautocomplete.TokenCompleteTextView.onFocusChanged(TokenCompleteTextView.java:830)

**Comment by mgod** [comment] 2017-02-22 18:32
Are you able to reproduce this issue using the sample project? These are often extremely specific bugs and I won't be able to help much unless I can reproduce the issue on my end.

**Comment by lpflpy** [comment] 2017-02-23 12:43
public void performCollapse(boolean hasFocus) {
....
for (TokenImageSpan span : hiddenSpans) {
                    removeSpan(span);
  }
}

why removeSpan one by one , but not text.delete(int st,int end)?
 when  the count of hiddenSpans is beyond 100, anr will happen

**Comment by wei-gong** [comment] 2018-07-05 07:31
I met the same problem, performCollapse will cause ANR when the count of hiddenSpans is big enough!

**Comment by mgod** [comment] 2018-07-05 16:56
I'm having trouble understanding when in reasonable use the number of spans would ever get to 100. Can you describe your use case a bit?

We use `removeSpan` because the expected number of spans is pretty small and it makes it easier to have consistent behavior.

**Comment by wei-gong** [comment] 2018-07-06 01:47
I use it as recipients view in the scene of sending emails to a 100 members team.

**Comment by foodied** [comment] 2018-08-31 05:50
Both `removeSpan()` and `insertSpan()` are responsible for anr's.

**Comment by mgod** [comment] 2018-08-31 14:46
Thanks for the feedback. I'm happy to look into this (and I'm re-writing a lot of the span handling right now), but I'm still not able to reproduce this using the sample project, so I'm not sure how to tell if I've fixed the problem.

**Comment by mgod** [comment] 2018-09-03 14:44
Ah, this view probably isn't suitable for being used in a recyclerview.

Adding and removing items is necessarily a little slow in order to build the internal data structures necessary to display the tokens while allowing editing. I'd recommend looking at something like FlowLayout or ChipDrawable fro displaying lots of rows with multiple chips in each row.

**Comment by Krishnakantkhetan** [comment] 2019-01-28 11:12
I met the same problem, performCollapse takes a lot of time (more than 30secs) to collapse when there are more than 100 spans.
Same issue can be reproduced in the sample app. Below are the steps:
1. - Open Sample APP.
2. - Add 100 spans by clicking 'ADD RANDOM TOKEN' button.
3. - Click on 'test focus loss'.

Observe the behaviour, control gets stuck for more than 30 secs. When number of spans 200 it goes crazy.

**Comment by mgod** [comment] 2019-03-09 15:49
While this view probably still isn't a great choice in a recycler view, the slow collapse ANR should be resolved in version 3.0.0

**Closed by mgod** 2019-03-09 15:49 UTC
