### ISSUE TITLE
Scrollbars...

### ISSUE THREAD

**Issue by vpdsouza** [splitwise/TokenAutoComplete#286] opened 2017-02-08 16:07 UTC
Great tool/control and thank you very much for that.

How can I force the scrollbars?  Is it even possible?

Also, it works great for two rows but as I add recipients and the rows grow more than two second, third and subsequent rows slightly overlap as you see below.  How can I fix this issue?

![image](https://cloud.githubusercontent.com/assets/840274/22745457/9a34105c-edee-11e6-9add-1be100889411.png)

**Comment by mgod** [comment] 2017-02-08 16:25
It's an ```EditText``` subclass, so you'd need to do whatever it takes to get an ```EditText``` to show scrollbars (```android:scrollbars="vertical"``` in the XML?).

The other issue is a duplicate of #245

**Closed by mgod** 2017-02-08 16:25 UTC
