### ISSUE TITLE
In the sample app,when I enter "abc" , it' will complete into "abc@example.com" and "abc" ( see image below)

### ISSUE THREAD

**Issue by duckm8795** [splitwise/TokenAutoComplete#281] opened 2017-02-02 22:47 UTC
This happens only on real devices ( my emulator still works) and it only happens when i press done button in the keyboard ( when i'm using ",", it still works). How can i fix it ?
![screenshot from 2017-02-03 05-41-04](https://cloud.githubusercontent.com/assets/20036318/22571845/283bfcbc-e9d4-11e6-8928-e8b07474f6f5.png)

**Comment by duckm8795** [comment] 2017-02-03 10:55
I  figured it out . On my devices , I installed third-party keyboard , when I change to my original keyboard of my phones , this bug doesn't happen.

**Comment by mgod** [comment] 2017-02-06 16:00
This is a duplicate of #242.

**Closed by mgod** 2017-02-06 16:00 UTC
